version: "3.7"
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    #command: "mysqld --init-file /data/application/init.sql"
    #volumes:
      #- ./init.sql:/data/application/init.sql
      # hello

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 7999:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
